apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: bitnami/spark:latest
          env:
            - name: SPARK_MODE
              value: "master"
            - name: SPARK_MASTER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPARK_MASTER_PORT
              value: "7077"
            - name: SPARK_MASTER_WEBUI_PORT
              value: "8080"
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: "yes"
            - name: SPARK_RPC_AUTHENTICATION_SECRET
              value: "mysecret"
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: "yes"
          ports:
            - containerPort: 7077
            - containerPort: 8080
