apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  ports:
    - name: spark-port
      port: 7077
      targetPort: 7077
      protocol: TCP
    - name: web-ui
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: spark-master
  type: ClusterIP
